"""Version-two Setup state contracts."""

from .models import (
    AccessStaleState,
    AcceptedReadiness,
    ApprovalPendingState,
    GithubConnectedState,
    InstallationSuspendedState,
    InstalledNoRepositoriesState,
    NoScanReadiness,
    RejectedReadiness,
    RepositoryReadyState,
    RepositoryReadyWriteState,
    RepositorySelectionState,
    SetupBootstrap,
    SetupCapabilities,
    SetupGithubIdentity,
    SetupInstallation,
    SetupLocalRun,
    SetupMachineToken,
    SetupReadiness,
    SetupReadinessKind,
    SetupRepository,
    SetupRepositoryPage,
    SetupRepositoryPermission,
    SetupSelection,
    SetupSelectionStatus,
    SetupState,
    SetupStateKind,
    SetupTokenStatus,
    SignedOutState,
)
from .service import repository_page_payload, setup_payload, validate_repository_page, validate_setup_bootstrap

__all__ = [
    "AccessStaleState",
    "AcceptedReadiness",
    "ApprovalPendingState",
    "GithubConnectedState",
    "InstallationSuspendedState",
    "InstalledNoRepositoriesState",
    "NoScanReadiness",
    "RejectedReadiness",
    "RepositoryReadyState",
    "RepositoryReadyWriteState",
    "RepositorySelectionState",
    "SetupBootstrap",
    "SetupCapabilities",
    "SetupGithubIdentity",
    "SetupInstallation",
    "SetupLocalRun",
    "SetupMachineToken",
    "SetupReadiness",
    "SetupReadinessKind",
    "SetupRepository",
    "SetupRepositoryPage",
    "SetupRepositoryPermission",
    "SetupSelection",
    "SetupSelectionStatus",
    "SetupState",
    "SetupStateKind",
    "SetupTokenStatus",
    "SignedOutState",
    "repository_page_payload",
    "setup_payload",
    "validate_repository_page",
    "validate_setup_bootstrap",
]
